[tool.poetry]
name = "hstsparser"
version = "0.1.0"
description = ""
authors = ["Daniel Milnes <thebeanogamer@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
argparse = "^1.4"
PTable = "^0.9.2"

[tool.poetry.dev-dependencies]
flake8 = "=3.7.9"
flake8-bandit = "=1.0.2"
flake8-bugbear = "=19.8.0"
flake8-import-order = "=0.18"
flake8-string-format = "=0.2.3"
flake8-tidy-imports = "=3.0.0"
flake8-todo = "=0.7"
safety = "=1.8.5"
dodgy = "=0.1.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
